### ISSUE TITLE
可以请求一下源码吗

### ISSUE THREAD

**Issue by yuuko0623** [kallydev/youth#1]
最近在学习社工知识
请问可以请求一下privacy项目的源码吗
这是我的邮箱tixiangzhi@gmail.com
多谢！代码路上共勉～

**Comment by kallydev** [comment]
我也没有，但是可以在 [Forks](https://github.com/kallydev/privacy/network/members) 里找。另外在 GitHub 发布无关 Issues 不是一种值得提倡的行为。如有要事，我的 [Profile](https://github.com/kallydev) 里有可选联系方式。
